Added Simplified Chinese (zh_cn.json)
UltimatChamp/BetterGrassify pull request #23
Opened 2024-08-25 06:41 UTC by kuhananxianglai

Added Simplified Chinese localization.

This is my first time submitting a translation file on GitHub! In fact, I think there are not many similar mods out there now, but bettergrassify has a convenient function of adding more custom blocks, so that I can also process some new blocks in other mods, but there is no Simplified Chinese yet. So I submitted this translation and explained some contents, hoping it can be adopted, thank you, very good mod!

2024-08-26 06:53 UTC, UltimatChamp requested changes
Thanks for your time, and happy to hear that you liked the mod! I've requested some changes to be done. Can you please rectify them, before I can merge your PR?

2024-08-26 06:53 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +    "bettergrass.betterGrassMode": "预设模式",
Can you change this to something like **Better Grass Mode**, instead of "Preset Mode"?

2024-08-26 06:53 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +    "bettergrass.betterGrassMode.desc": "§4关 §r- 原版默认\n§3流畅 §r- 方块的顶部纹理将应用于其所有侧面（性能较高的快速全覆盖）\n§d高品质 §r- 方块的顶部纹理将动态应用于它的所需侧面（性能较低但更花哨美观）",
`（性能较高的快速全覆盖）` - Is there a one-word value like "fast" that can be used here?
`（性能较低但更花哨美观）` - This too!

2024-08-26 06:53 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +    "bettergrass.dirtPaths.desc": "连接土径（默认关闭）\n\n§c或许还存在着一些视觉上的小瑕疵，会显示1像素高的下方方块纹理\n已提交GitHub！",
`（默认关闭）` - this isn't required.
`会显示1像素高的下方方块纹理\n已提交GitHub！` - this also isn't

2024-08-26 06:53 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +    "bettergrass.farmLands.desc": "连接耕地（默认关闭）\n\n§c或许还存在着一些视觉上的小瑕疵，会显示1像素高的下方方块纹理\n已提交GitHub！",
same as dirt paths

2024-08-26 06:53 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +    "bettergrass.moreBlocks.desc": "添加更多可自定义的草类方块，这对那些想要让更多方块实现此类效果的人来说非常有用，输入命名空间ID",
`Grass-like blocks that should be connected on slopes.` is enough, here.

2024-08-26 06:53 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +
```suggestion
}

```

2024-08-26 06:56 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +  }
```suggestion
}
```

2024-08-26 06:56 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +
```suggestion

```

2024-08-26 07:00 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/zh_cn.json
> +
this should be replaced with a proper newline

2024-08-26 08:25 UTC, kuhananxianglai commented
Oh, I'm sorry about these errors, which interrupt your work and time, and thank you for pointing them out! 
These problems are my own, haha. Objectively speaking, they should be caused by some differences in cultural expression. However, I have completed the modifications according to your requirements.
It is no exaggeration to say that I am a newbie and I am not very familiar with the process of using GitHub to work. I deleted the (zh_cn.json) file in my "Fork" and re-uploaded the corrected file. I don't know if this is compliant, but I can see the prompt in red: "All checks have failed" , hope this is not a big problem...
So I clicked "Re-request review" If you have any more questions please let me know, thank you very much for your reply and work ;)
I believe that mods will get better and better with everyone’s efforts! Best wishes!

2024-09-06 07:32 UTC, UltimatChamp approved these changes

2024-09-06 07:33 UTC, UltimatChamp commented
Thanks!

2024-09-06 07:34 UTC, merged