Portuguese Brazilian Localization
UltimatChamp/BetterGrassify pull request #25
Opened 2024-09-19 15:16 UTC by Alstin112

2024-09-22 05:52 UTC, UltimatChamp requested changes
@Alstin112 I've recently added some new options.
Could you please translate them as well? I've included them in your Pull Request repo.

2024-09-22 05:56 UTC, UltimatChamp commented on src/main/resources/assets/bettergrass/lang/pt_br.json
> +  "bettergrass.betterGrassMode.desc": "§4Desligado §r- Blocos de grama aparentam normal\n§3Rápido §r- A textura do topo da grama será aplicado em todos os lados do bloco (rápido)\n§dBonito §r- A text
```suggestion
  "bettergrass.betterGrassMode.desc": "§4Não §r- Blocos de grama aparentam normal\n§3Rápidas §r- A textura do topo da grama será aplicado em todos os lados do bloco (rápido)\n§dDetalhadas §r- A textura do topo de grama será aplicado dinamicamente aos lados do bloco (lento)",
```

2024-09-22 17:55 UTC, Alstin112 reviewed
Translated the new text

2024-09-22 17:55 UTC, Alstin112 commented on src/main/resources/assets/bettergrass/lang/pt_br.json
> +  "bettergrass.betterSnowMode": "Better Snow",
```suggestion
  "bettergrass.betterSnowMode": "Neve Melhorada",
```

2024-09-22 17:55 UTC, Alstin112 commented on src/main/resources/assets/bettergrass/lang/pt_br.json
> +  "bettergrass.betterSnowMode.optifine": "OptiFine-like",
```suggestion
  "bettergrass.betterSnowMode.optifine": "Tipo-OptiFine",
```

2024-09-22 17:55 UTC, Alstin112 commented on src/main/resources/assets/bettergrass/lang/pt_br.json
> +  "bettergrass.betterSnowMode.lambda": "LambdaBetterGrass-like",
```suggestion
  "bettergrass.betterSnowMode.lambda": "Tipo-LambdaBetterGrass",
```

2024-09-22 17:55 UTC, Alstin112 commented on src/main/resources/assets/bettergrass/lang/pt_br.json
> +  "bettergrass.dirtPaths.desc": "Conecta caminhos de grama também!\n\n§cTalvez cause alguns bugs visuais!",
```suggestion
  "bettergrass.dirtPaths.desc": "Conecta caminho de terra também!\n\n§cTalvez cause alguns bugs visuais!",
```

2024-09-22 17:55 UTC, Alstin112 commented on src/main/resources/assets/bettergrass/lang/pt_br.json
> +  "bettergrass.betterGrassMode": "Modo de Melhor Grama",
```suggestion
  "bettergrass.betterGrassMode": "Modo de Grama Melhorada",
```

2024-09-24 10:43 UTC, UltimatChamp approved these changes

2024-09-24 10:44 UTC, merged